name: firebase_ui
description: Firebase auth UI, dart package to mimic the firebaseUI(Google, Facebook, Email supported)
version: 1.0.10
author: Nicholas Bowler <crucifixx25@gmail.com>
homepage: https://github.com/Maliffic/firebase_ui

environment:
  sdk: ">=2.5.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^2.1.5

  device_info: ^0.4.2+4

  firebase_auth: ^0.16.0
  firebase_auth_platform_interface: ^1.1.8

  google_sign_in: ^4.5.1
  # flutter_facebook_login: ^3.0.0

  sign_in_with_apple: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/apple.png
