name: firebase_ui
description: Firebase auth UI, dart package to mimic the firebaseUI(Google, Facebook, Email supported)
version: 1.0.10
author: Nicholas Bowler <crucifixx25@gmail.com>
homepage: https://github.com/Maliffic/firebase_ui

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.15.3

  google_sign_in: ^4.1.1
  # flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png
